# Generated by Django 3.1.2 on 2020-11-04 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='PK')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('username', models.CharField(max_length=20, verbose_name='이름')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('modify_datetime', models.DateTimeField(auto_now_add=True, verbose_name='정보 수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='super유저')),
                ('userid', models.CharField(max_length=20, unique=True, verbose_name='사용자 ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'users',
            },
        ),
    ]
