# Generated by Django 3.1.1 on 2020-09-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_content', models.TextField(blank=True)),
                ('as_datetime', models.DateTimeField(auto_now_add=True)),
                ('as_modify_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_content', models.CharField(blank=True, max_length=200)),
                ('cm_datetime', models.DateTimeField(auto_now_add=True)),
                ('cm_modify_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lk_datetime', models.DateTimeField(auto_now=True)),
                ('li_ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=225)),
                ('post_content', models.TextField(blank=True)),
                ('post_datatime', models.DateTimeField(auto_now_add=True)),
                ('post_modify_datatime', models.DateTimeField(auto_now=True, null=True)),
                ('post_answer_count', models.IntegerField(null=True)),
                ('post_hits', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('answer', models.ManyToManyField(blank=True, to='bbp.Answer')),
                ('post', models.ManyToManyField(blank=True, to='bbp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Post_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbp.like')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbp.post')),
            ],
        ),
    ]
