# Generated by Django 3.1.1 on 2020-09-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='as_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='as_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cm_content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cm_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_answer_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_datatime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_modify_datatime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
